---
layout: post
title: "xviv: from custom IP to bitstream"
date: 2025-04-10
description: "A complete walkthrough of the xviv workflow — defining a custom AXI-Stream IP, wiring it into a block design, and running synthesis to a bitstream."
tags: [fpga, vivado, tools]
reading_time: 35
---

`xviv` is a command-line controller for Xilinx Vivado and Vitis. It drives the full FPGA development workflow — IP packaging, block design, synthesis, simulation, and MicroBlaze firmware — from a single `project.toml` file and a set of shell commands. You never need to open the Vivado GUI except for interactive block design editing.

This tutorial walks through a complete example: a custom AXI-Stream data pipeline IP, connected to a Zynq PS in a block design, synthesised to a bitstream for the Pynq-Z2 board.

<!--more-->

## Installation

```bash
pip install -e /path/to/xviv
```

Enable tab-completion (run once):

```bash
# zsh
echo 'eval "$(register-python-argcomplete xviv)"' >> ~/.zshrc
source ~/.zshrc

# bash
echo 'eval "$(register-python-argcomplete xviv)"' >> ~/.bashrc
source ~/.bashrc
```

Vivado must already be installed. The default path is `/opt/Xilinx/Vivado/2024.1`. If yours differs, set it in `project.toml` as shown below.

---

## Project layout

Before touching any commands, set up the directory structure. Everything below is a convention — xviv does not enforce it — but following it means the default `project.toml` settings will work without modification.

```
my_project/
├── project.toml
├── srcs/
│   ├── rtl/
│   │   └── axis_pipeline/
│   │       ├── axis_pipeline.sv       ← IP top module
│   │       └── pipeline_stage.sv      ← submodule
│   ├── sim/
│   │   └── tb_axis_pipeline.sv
│   └── xdc/
│       ├── axis_pipeline.xdc          ← IP constraints
│       └── top.xdc                    ← top-level pin assignments
├── scripts/                           ← generated by xviv, committed to git
│   ├── ip/
│   ├── bd/
│   └── synth/
└── build/                             ← generated, git-ignored
```

Add `build/` to your `.gitignore`:

```
build/
```

---

## project.toml

Create `project.toml` in the project root. This is the single source of truth for every `xviv` command.

```toml
# ── Vivado settings ───────────────────────────────────────────────────────────
[vivado]
path        = "/opt/Xilinx/Vivado/2024.1"
max_threads = 8
mode        = "batch"       # batch = no GUI; tcl = interactive TCL console

# ── Vitis settings (only needed for MicroBlaze flows) ─────────────────────────
[vitis]
path = "/opt/Xilinx/Vitis/2024.1"

# ── Build output directories ─────────────────────────────────────────────────
[build]
dir         = "build"
ip_repo     = "build/ip"          # packaged IPs land here
bd_dir      = "build/bd"          # block design .bd files
wrapper_dir = "build/wrapper"     # BD-generated HDL wrappers

# ── RTL sources ──────────────────────────────────────────────────────────────
# These globs apply to synthesis and simulation unless overridden per-entry.
[sources]
rtl     = ["srcs/rtl/**/*.sv", "srcs/rtl/**/*.v"]
wrapper = ["build/wrapper/**/*.sv"]
sim     = ["srcs/sim/**/*.sv"]

# ── FPGA target ──────────────────────────────────────────────────────────────
[fpga]
part       = "xc7z020clg400-1"
board_part = "tul.com.tw:pynq-z2:part0:1.0"
board_repo = "/opt/board_files"     # omit if using the built-in Vivado catalog
```

### Multiple FPGA targets

If you need to target more than one board, replace `[fpga]` with named subtables and reference them from individual IP, BD, or synthesis entries:

```toml
[fpga.z2]
part       = "xc7z020clg400-1"
board_part = "tul.com.tw:pynq-z2:part0:1.0"

[fpga.u50]
part = "xcu50-fsvh2104-2-e"
```

Then in any `[[ip]]`, `[[bd]]`, or `[[synthesis]]` entry, add `fpga = "z2"` or `fpga = "u50"`. Entries without a `fpga` key use the default `[fpga]` table.

---

## The example IP: axis_pipeline

The IP we will package is a parametric AXI-Stream pipeline with a configurable number of register stages and data width. It is a deliberately simple design — the goal is to illustrate the packaging workflow, not the RTL.

### RTL

`srcs/rtl/axis_pipeline/axis_pipeline.sv`:

```systemverilog
module axis_pipeline #(
    parameter int DATA_WIDTH  = 32,
    parameter int NUM_STAGES  = 4
) (
    input  logic                  aclk,
    input  logic                  aresetn,

    // Slave AXI-Stream input
    input  logic [DATA_WIDTH-1:0] s_axis_tdata,
    input  logic                  s_axis_tvalid,
    output logic                  s_axis_tready,
    input  logic                  s_axis_tlast,

    // Master AXI-Stream output
    output logic [DATA_WIDTH-1:0] m_axis_tdata,
    output logic                  m_axis_tvalid,
    input  logic                  m_axis_tready,
    output logic                  m_axis_tlast
);

    logic [DATA_WIDTH-1:0] data_pipe  [NUM_STAGES];
    logic                  valid_pipe [NUM_STAGES];
    logic                  last_pipe  [NUM_STAGES];

    always_ff @(posedge aclk) begin
        if (!aresetn) begin
            valid_pipe[0] <= 1'b0;
            last_pipe[0]  <= 1'b0;
            data_pipe[0]  <= '0;
        end else if (s_axis_tvalid && s_axis_tready) begin
            data_pipe[0]  <= s_axis_tdata;
            valid_pipe[0] <= s_axis_tvalid;
            last_pipe[0]  <= s_axis_tlast;
        end else begin
            valid_pipe[0] <= 1'b0;
        end
    end

    generate
        for (genvar i = 1; i < NUM_STAGES; i++) begin : gen_stages
            always_ff @(posedge aclk) begin
                if (!aresetn) begin
                    valid_pipe[i] <= 1'b0;
                    data_pipe[i]  <= '0;
                end else begin
                    data_pipe[i]  <= data_pipe[i-1];
                    valid_pipe[i] <= valid_pipe[i-1];
                    last_pipe[i]  <= last_pipe[i-1];
                end
            end
        end
    endgenerate

    assign s_axis_tready = m_axis_tready;
    assign m_axis_tdata  = data_pipe[NUM_STAGES-1];
    assign m_axis_tvalid = valid_pipe[NUM_STAGES-1];
    assign m_axis_tlast  = last_pipe[NUM_STAGES-1];

endmodule
```

The port naming follows Vivado's AXI-Stream inference conventions exactly:

- Clock: `aclk`
- Reset: `aresetn` (active-low, matching `xilinx.com:signal:reset_rtl:1.0`)
- Slave interface prefix: `s_axis_`
- Master interface prefix: `m_axis_`

Vivado's interface inference engine matches port suffixes (`tdata`, `tvalid`, `tready`, `tlast`) to the `xilinx.com:interface:axis_rtl:1.0` abstraction. The `s_` / `m_` prefix determines interface mode. Stick to these conventions and inference is automatic.

---

## Step 1 — Add the IP entry to project.toml

```toml
[[ip]]
name    = "axis_pipeline"
vendor  = "myorg.com"
library = "user"
version = "1.0"
top     = "axis_pipeline"
rtl     = ["srcs/rtl/axis_pipeline/**/*.sv"]
xdc     = ["srcs/xdc/axis_pipeline.xdc"]
hooks   = "scripts/ip/axis_pipeline_1_0.tcl"
```

| Key       | Purpose |
|---|---|
| `name`    | Identifier passed to every `--ip` command |
| `vendor`  | Forms the VLNV: `myorg.com:user:axis_pipeline:1.0` |
| `top`     | HDL module name — must match the `module` declaration exactly |
| `rtl`     | Glob patterns for source files, relative to `project.toml` |
| `xdc`     | Constraint files used during full synthesis |
| `hooks`   | TCL hooks file, auto-generated by `ip-config` |

---

## Step 2 — Generate the hooks file

```bash
xviv ip-config --ip axis_pipeline
```

Creates `scripts/ip/axis_pipeline_1_0.tcl` with stub procs for each hook point:

```tcl
# Hook procs — xviv create-ip — axis_pipeline

proc ipx_add_files {} {
    # Called after the IP edit project is opened.
    # Add extra RTL sources here beyond what project.toml specifies.
    # Example:
    #   add_files [glob -nocomplain ./srcs/rtl/axis_pipeline/*.sv]
}

proc ipx_merge_changes {} {
    # Called after ipx::merge_project_changes.
    # Correct anything the merge got wrong, or add custom file properties.
}

proc ipx_infer_bus_interfaces {} {
    # Called after the default AXI-Stream / AXI-MM inference.
    # Add inference calls for any additional bus standards your IP uses.
    # Example (APB):
    #   ipx::infer_bus_interfaces \
    #       xilinx.com:interface:apb_rtl:1.0 [ipx::current_core]
}

proc ipx_add_params {} {
    # Called after HDL parameters are added to the IP customisation GUI.
    # Use to reorder, rename, or add display conditions.
    # Example — move DATA_WIDTH to the top of Page 0:
    #   ipgui::move_param \
    #       -component [ipx::current_core] \
    #       -order 0 \
    #       [ipgui::get_guiparamspec \
    #           -name "DATA_WIDTH" \
    #           -component [ipx::current_core]] \
    #       -parent [ipgui::get_pagespec \
    #           -name "Page 0" \
    #           -component [ipx::current_core]]
}

proc ipx_add_memory_map {} {
    # Called after bus interfaces are finalised.
    # For AXI-Lite slave IPs: add memory map entries for registers here.
    # Not needed for a pure AXI-Stream IP like axis_pipeline.
}
```

For `axis_pipeline`, the defaults are fine. Vivado will find the AXI-Stream interfaces automatically from the port names. You do not need to edit this file for the example.

For a real IP with unusual port naming, multiple bus standards, or a custom parameter GUI, edit the stubs before running `create-ip`.

---

## Step 3 — Package the IP

```bash
xviv create-ip --ip axis_pipeline
```

Vivado runs in batch mode. The log shows seven stages:

```
INFO: [+0m00s] Scaffolding IP skeleton - axis_pipeline_1_0
INFO: [+0m04s] Stripping default AXI-Lite scaffold
INFO: [+0m05s] Adding RTL sources
INFO: [+0m07s] Inferring bus interfaces
INFO: [+0m09s] Exposing HDL parameters
INFO: [+0m10s] Wiring AXI-Lite memory maps
INFO: [+0m11s] Finalising and saving IP
INFO: IP creation complete - 0m11s
```

What each stage does:

**Scaffold** — `create_peripheral` creates the IP skeleton at `build/ip/axis_pipeline_1_0/`. Vivado adds a default AXI-Lite interface to everything it scaffolds.

**Strip scaffold** — the default AXI-Lite interface, its memory map, and the boilerplate stub Verilog files are removed. For `axis_pipeline` we only want AXI-Stream, not AXI-Lite.

**Add RTL** — your source files from the `rtl` glob are added to the edit project. `ipx_add_files` is called here if you need to add additional files programmatically.

**Infer interfaces** — `ipx::infer_bus_interfaces` is called for AXI-Stream and AXI-MM. It scans port names and groups matching ports into bus interface objects. For `axis_pipeline` it will find `S_AXIS` (slave, from `s_axis_*`) and `M_AXIS` (master, from `m_axis_*`), and separate clock and reset signal interfaces for `aclk` and `aresetn`.

**Expose params** — `DATA_WIDTH` and `NUM_STAGES` are added to the IP customisation GUI so users can set them when they instantiate the IP in a block design.

**Memory maps** — no-op for a pure AXI-Stream IP. For an AXI-Lite slave, this stage creates the register map that Vivado uses to generate address decode logic.

**Finalise** — `ipx::check_integrity` verifies the component.xml is well-formed, and `ipx::save_core` writes it to disk.

The final artefact is `build/ip/axis_pipeline_1_0/component.xml`. The IP is now registered in the local IP repository at `build/ip/`.

### Verify the packaged IP

```bash
xviv edit-ip --ip axis_pipeline
```

Opens the IP edit project in the Vivado GUI. Check:

- **Ports and Interfaces tab** — `S_AXIS` and `M_AXIS` should appear as AXI-Stream interfaces. `CLK` and `RST` should be signal-level clock and reset interfaces.
- **Parameters tab** — `DATA_WIDTH` and `NUM_STAGES` should both appear with their default values.
- **Compatibility tab** — the part family should match what is in `[fpga]`.

Close Vivado when satisfied. No changes are needed.

---

## Step 4 — Add the block design entry to project.toml

```toml
[[bd]]
name       = "system"
fpga       = "z2"
xdc        = ["srcs/xdc/top.xdc"]
hooks      = "scripts/bd/system_hooks.tcl"
export_tcl = "scripts/bd/system.tcl"
```

`export_tcl` is the path where `export-bd` writes the re-runnable TCL script. On subsequent `create-bd` runs, xviv sources this file to recreate the BD non-interactively. This is how the BD is version-controlled: the exported TCL is committed to git; the `.bd` binary is not.

---

## Step 5 — Generate the BD hooks file

```bash
xviv bd-config --bd system
```

Creates `scripts/bd/system_hooks.tcl`:

```tcl
set ::_bd_design_tcl \
    [file join [file dirname [info script]] "system.tcl"]

proc bd_design_config { parentCell } {
    global _bd_design_tcl

    if { [file exists $_bd_design_tcl] } {
        puts "INFO: Sourcing exported BD TCL — $_bd_design_tcl"
        source $_bd_design_tcl
        xviv_refresh_bd_addresses
        validate_bd_design
        save_bd_design
        exit 0
    } else {
        puts "INFO: No exported BD TCL found."
        puts "INFO: Opening GUI for interactive design."
        puts "INFO: When done, run:  xviv export-bd --bd system"
        start_gui
    }
}
```

The logic is: if `scripts/bd/system.tcl` exists (either a real file or a symlink), recreate the BD from it and exit. If it does not exist yet, open the GUI.

---

## Step 6 — Create the block design

```bash
xviv create-bd --bd system
```

Because `scripts/bd/system.tcl` does not exist yet, Vivado opens the GUI. You will have an empty block design canvas.

### Add the Zynq PS

Click **Add IP** (or `Ctrl+I`) and search for `ZYNQ7 Processing System`. Double-click to place it. A green banner appears at the top: click **Run Block Automation**, accept the defaults, and click OK. This configures the PS for the Pynq-Z2 board — DDR, MIO pins, clocks.

### Add the AXI DMA

Add IP → search `AXI Direct Memory Access`. Double-click to place it. Then double-click the block to open its configuration:

- Set **Width of Buffer Length Register** to `26` (supports transfers up to 64 MB).
- Disable **Enable Scatter Gather Engine** for simple register mode.
- Set **Stream Data Width** to `32` to match `DATA_WIDTH = 32` in the IP.
- Click OK.

### Add axis_pipeline

Add IP → search `axis_pipeline`. It appears under `myorg.com`. Double-click to place it. Double-click to configure:

- `DATA_WIDTH` = `32`
- `NUM_STAGES` = `4`
- Click OK.

### Connect the blocks

Click **Run Connection Automation** in the green banner. Enable all suggested connections and click OK. Vivado connects:

- PS AXI master → DMA control slave (`S_AXI_LITE`)
- DMA `M_AXIS_MM2S` → `axis_pipeline` `S_AXIS`
- `axis_pipeline` `M_AXIS` → DMA `S_AXIS_S2MM`
- `aclk` and `aresetn` → PS clock and interconnect reset
- DMA interrupt outputs → PS interrupt controller inputs

After automation, verify the data path manually by tracing connections on the canvas:

```
PS HP0 (AXI Master)
  └─► AXI DMA S_AXI_LITE      (control registers, base 0x4000_0000)
        M_AXIS_MM2S ──► axis_pipeline S_AXIS
                              M_AXIS ──► AXI DMA S_AXIS_S2MM
                                            M_AXI_S2MM ──► PS HP1 (AXI Slave)
```

The PS initiates a transfer by writing to the DMA control registers. The DMA streams data from DDR out of `M_AXIS_MM2S`, through `axis_pipeline`, and the pipeline output is written back to DDR via `S_AXIS_S2MM`.

### Assign addresses

Click the **Address Editor** tab at the top of the block design view. The DMA slave should already have an address assigned by the automation. If any slave shows `<unmapped>`, right-click it and select **Assign Address**.

Typical assignment for this design:

| Slave | Base Address | Range |
|---|---|---|
| `axi_dma_0 / S_AXI_LITE` | `0x4000_0000` | 64K |

### Validate

Press `F6` or **Tools → Validate Design**. Resolve any critical errors. Warnings about unconnected debug ports are normal and can be ignored.

### Save

`Ctrl+S`. Then close Vivado.

---

## Step 7 — Export the block design

```bash
xviv export-bd --bd system
```

Vivado reopens the BD, upgrades any stale IPs, and writes:

```
scripts/bd/system_abc1234.tcl     ← versioned file, commit this
scripts/bd/system.tcl             ← symlink to the above, commit this too
```

The symlink is what `bd_design_config` sources. When you export again after future edits, a new versioned file is written and the symlink is updated atomically. This gives you a complete history of every BD state in git with no binary files.

Commit both:

```bash
git add scripts/bd/
git commit -m "feat: system BD — DMA + axis_pipeline"
```

From this point forward, any team member can recreate the BD from scratch:

```bash
xviv create-bd --bd system   # sources system.tcl, no GUI
```

A `_dirty` suffix is appended to the tag when the working tree has uncommitted changes (`system_abc1234_dirty.tcl`). Do not treat dirty exports as authoritative.

---

## Step 8 — Generate BD output products

```bash
xviv generate-bd --bd system
```

Three things happen inside Vivado:

1. `generate_target all` — generates HDL sources for every IP in the BD: synthesis netlists, simulation models, and instantiation templates.
2. `validate_bd_design` — reruns design rule checks.
3. `make_wrapper` — generates `system_wrapper.sv`, the HDL top-level that instantiates the BD. The wrapper is copied to `build/wrapper/system_wrapper.sv`.

After this step you have a synthesisable HDL top module. The `[sources] wrapper` glob in `project.toml` picks it up automatically.

---

## Step 9 — Add the synthesis entry to project.toml

```toml
[[synthesis]]
top   = "system_wrapper"
fpga  = "z2"
xdc   = ["srcs/xdc/top.xdc"]
hooks = "scripts/synth/system_wrapper.tcl"
```

`top` must match the module declaration in `build/wrapper/system_wrapper.sv` exactly. The `xdc` here is for top-level constraints — timing constraints, IO pin assignments — not the IP-level constraints, which are already embedded in the BD output products.

A minimal `srcs/xdc/top.xdc` for the Pynq-Z2 (pure-PS design, no external pins):

```tcl
# Primary clock — 125 MHz from PS PL fabric clock 0
create_clock -period 8.000 -name clk_fpga_0 \
    [get_pins -hier -filter {NAME =~ */PS7_i/FCLKCLK[0]}]

# False paths on async PS reset
set_false_path \
    -from [get_pins -hier -filter {NAME =~ */PS7_i/FCLKRESETN[0]}]
```

### Generate synthesis hooks

```bash
xviv synth-config --top system_wrapper
```

Creates `scripts/synth/system_wrapper.tcl` with five stubs:

```tcl
proc synth_pre      {}  {}   # before synth_design
proc synth_post     {}  {}   # after synth_design, before place_design
proc place_post     {}  {}   # after place_design, before route_design
proc route_post     {}  {}   # after route_design, before write_bitstream
proc bitstream_post {}  {}   # after write_bitstream
```

Leave all stubs empty for this example. The hooks are useful when you need to set custom Vivado properties, run targeted DRC checks at a specific implementation stage, or copy artefacts mid-flow.

---

## Step 10 — Run synthesis

```bash
xviv synthesis --top system_wrapper
```

The full flow runs: synthesise → place → route → write bitstream → write XSA. Progress is logged with elapsed timestamps:

```
INFO: [+0m00s] Synthesis — system_wrapper  (sha: abc1234)
INFO: [+4m22s] Placement
INFO: [+6m51s] Routing
INFO: [+8m03s] Generating bitstream
INFO: Build complete — 8m09s
```

All outputs land in `build/synth/system_wrapper/`:

```
build/synth/system_wrapper/
├── post_synth.dcp
├── post_place.dcp
├── post_route.dcp
├── system_wrapper_abc1234.bit
├── system_wrapper_abc1234.xsa
├── system_wrapper.bit          ← symlink → system_wrapper_abc1234.bit
├── system_wrapper.xsa          ← symlink → system_wrapper_abc1234.xsa
└── build.json
```

`build.json` is written only when the run completes successfully:

```json
{
  "vivado_version": "2024.1",
  "part": "xc7z020clg400-1",
  "top": "system_wrapper",
  "sha_tag": "abc1234",
  "dirty": "false",
  "bitstream": "system_wrapper_abc1234.bit",
  "xsa": "system_wrapper_abc1234.xsa",
  "elapsed": "8m09s",
  "timestamp": "2025-04-10T14:22:01Z"
}
```

Use the presence of `build.json` as a success signal in CI pipelines — it is absent for failed or interrupted runs.

The git SHA is also embedded in the bitstream via `BITSTREAM.CONFIG.USR_ACCESS`. Bit 31 is the dirty flag; bits 27:0 are the 7-digit hex SHA. Firmware can read this back over JTAG at runtime to confirm exactly which build is running on the hardware.

### Report flags

```bash
xviv synthesis --top system_wrapper \
    --report-synth   \   # timing summary + utilisation after synthesis
    --report-place   \   # IO, clock utilisation, hierarchical util after placement
    --report-route       # DRC, methodology, power, timing after routing
```

Pass `--report-all` to enable all three. Reports are written to `build/synth/system_wrapper/reports/`.

### Opening a checkpoint

If timing fails or you want to inspect the routed design:

```bash
xviv open-dcp --top system_wrapper --dcp post_route
```

Valid values: `post_synth`, `post_place`, `post_route`. Opens the checkpoint in the Vivado GUI where you can run timing analysis, inspect the floorplan, or add placement constraints before re-running from that stage.

---

## Full command sequence

```bash
# Package the IP
xviv ip-config  --ip axis_pipeline
xviv create-ip  --ip axis_pipeline

# Create the block design (opens GUI on first run)
xviv bd-config  --bd system
xviv create-bd  --bd system

# After interactive design and save in GUI:
xviv export-bd  --bd system
xviv generate-bd --bd system

# Synthesise to bitstream
xviv synth-config --top system_wrapper
xviv synthesis    --top system_wrapper
```

The bitstream is at `build/synth/system_wrapper/system_wrapper.bit`.

---

## Iterating

### Changing the IP RTL

If you modify `axis_pipeline.sv`, repackage and rebuild:

```bash
xviv create-ip   --ip axis_pipeline
xviv generate-bd --bd system
xviv synthesis   --top system_wrapper
```

### Changing the block design

```bash
xviv edit-bd   --bd system        # opens Vivado GUI
# make changes, save, close Vivado
xviv export-bd --bd system        # commit the new versioned TCL
xviv generate-bd --bd system
xviv synthesis   --top system_wrapper
```

### Reviewing BD history

Because each export is a versioned file:

```bash
git log --oneline scripts/bd/
git diff scripts/bd/system_abc1234.tcl scripts/bd/system_def5678.tcl
```

---

## Common errors

**`FPGA part 'xc7z020...' is not in the installed Vivado part catalog`**
The `part` string in `[fpga]` is wrong or that device family was not selected during Vivado installation. Run `get_parts *z020*` in a Vivado TCL console to find the correct string.

**`IP 'axis_pipeline' not found`**
Either `create-ip` has not been run, or `build.ip_repo` in `project.toml` does not match where the IP was created. Check that `build/ip/axis_pipeline_1_0/component.xml` exists.

**`BD file not found`**
`create-bd` has not been run yet, or `build.bd_dir` in `project.toml` does not match. Check that `build/bd/system/system.bd` exists.

**`Hooks file is configured but does not exist`**
Run `xviv ip-config --ip <n>` or `xviv bd-config --bd <n>` first, then re-run.

**`No RTL or wrapper source files were added`**
The glob patterns in `[sources]` matched no files. Confirm the paths are relative to `project.toml` and the files exist.

**`top module not found` during synthesis**
The `top` field in `[[synthesis]]` does not match the module name in `build/wrapper/system_wrapper.sv`. Open the wrapper file and check the `module` declaration at the top.

**Timing failure**
Open the post-route checkpoint with `xviv open-dcp --top system_wrapper --dcp post_route`, run `report_timing_summary` in the Vivado TCL console, and identify the failing paths. Add timing exceptions or floorplan constraints to `srcs/xdc/top.xdc` and re-run synthesis.

**`build.json` absent after a run**
The build did not complete. Check `build/xviv/xviv.log`. Common causes: DRC critical warnings promoted to errors, disk space exhausted, or a licensing issue for an encrypted IP.